### ISSUE TITLE
1.1.0 broke Nginx support 

### ISSUE THREAD

**Issue by urluba** [aws/aws-nitro-enclaves-acm#53]
Hi,

Running Amazon Linux 2 on a m6a, I am unable to use version 1.1.0-1 of the RPM with Nginx.

`systemctl status nginx -l` tells me he can't load the private key:
```
Nginx is unable to load 
Dec 29 12:45:50 i-013dfb51ffc42f1ce nginx[5758]: nginx: [emerg] cannot load certificate key "engine:pkcs11:pkcs11:model=p11ne-token;manufacturer=Amazon;token=nginx-acm-internal;id=%01;object=acm-key;type=private?pin-value=123456": ENGINE_load_private_key() failed (SSL: error:80067065:pkcs11 engine:ctx_load_privkey:object not found error:26096080:engine routines:ENGINE_load_private_key:failed loading private key)
```

The stanza file is:
```nginx
ssl_certificate_key "engine:pkcs11:pkcs11:model=p11ne-token;manufacturer=Amazon;token=nginx-acm-internal;id=%01;object=acm-key;type=private?pin-value=123456";
ssl_certificate "/run/nitro_enclaves/acm/nginx-cert-123456.pem";
```
Certificate located in `run/nitro_enclaves/acm/nginx-cert-...` is ok

And config file:
```yaml
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
enclave:
  cpu_count: 2
  memory_mib: 256
options:
  nginx_force_start: false
  nginx_reload_wait_ms: 20000
tokens:
  - label: nginx-acm-internal
    source:
      Acm:
        certificate_arn: "arn:aws:acm:earth-616:123456:certificate/123456"
    target:
      NginxStanza:
        path: /etc/nginx/acm/internal.conf
        user: nginx
```

Error happens with both an upgrade or a clean install. 
A rollback to RPM 1.0.2 solves the issue.
